# Generated by Django 5.1.4 on 2025-01-21 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('TEXT', 'Text Message'), ('IMAGE', 'Image Message'), ('VIDEO', 'Video Message'), ('AUDIO', 'Audio Message'), ('MULTIPLE', 'Multiple Messages'), ('DOCUMENT', 'Document'), ('LOCATION', 'Location'), ('CONTACT', 'Contact'), ('STICKER', 'Sticker'), ('SYSTEM', 'System Message')], default='TEXT', max_length=20),
        ),
    ]
