# Generated by Django 5.1.4 on 2025-01-17 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0002_researchpaper_averagereadingtime_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='researchpaper',
            old_name='AverageReadingTime',
            new_name='average_reading_time',
        ),
    ]
