// data.js (example file or inline in your component)
export const papersData = [
    {
      "id": "a1888554-ed25-4b7f-997f-d0fcbd1d37a5",
      "title": "Learning Chordal Markov Networks by Constraint Satisfaction",
      "abstract": "We investigate the problem of learning the structure of a Markov network ...",
      "authors": [
        "Jukka Corander",
        "Tomi Janhunen",
        "Jussi Rintanen",
        "Henrik Nyman",
        "Johan Pensar"
      ],
      "source": "Science direct",
      "url": "http://arxiv.org/abs/1310.0927v1",
      "pdf_url": "http://arxiv.org/pdf/1310.0927v1",
      "categories": ["Artificial Intelligence"],
      "publication_date": "2025-01-10",
      "created_at": "2025-01-16T09:33:48.421124Z",
      "is_bookmarked": false,
      "bookmark_id": null,
      "active_bookmarks_count": 0,
      "bookmarks": []
    },
    {
      "id": "6ac14eb0-fdd5-464f-b467-cb304aefcfa9",
      "title": "Iterated Variable Neighborhood Search for the resource constrained multi-mode multi-project scheduling problem",
      "abstract": "The resource constrained multi-mode multi-project scheduling problem (RCMMMPSP) ...",
      "authors": ["Martin Josef Geiger"],
      "source": "abcd",
      "url": "http://arxiv.org/abs/1310.0602v1",
      "pdf_url": "http://arxiv.org/pdf/1310.0602v1",
      "categories": ["Artificial Intelligence"],
      "publication_date": "2025-01-10",
      "created_at": "2025-01-16T09:33:48.346389Z",
      "is_bookmarked": false,
      "bookmark_id": null,
      "active_bookmarks_count": 0,
      "bookmarks": []
    },
    {
      "id": "ec42c731-4ba5-4dcc-bd28-b7239a2b3bfc",
      "title": "Proceedings of the Twenty-Ninth Conference on Uncertainty in Artificial Intelligence (2013)",
      "abstract": "This is the Proceedings of the Twenty-Ninth Conference on Uncertainty in ...",
      "authors": ["Ann Nicholson", "Padhriac Smyth"],
      "source": " direct",
      "url": "http://arxiv.org/abs/1309.7971v2",
      "pdf_url": "http://arxiv.org/pdf/1309.7971v2",
      "categories": ["Intelligence"],
      "publication_date": "2025-01-10",
      "created_at": "2025-01-16T09:33:48.279146Z",
      "is_bookmarked": false,
      "bookmark_id": null,
      "active_bookmarks_count": 0,
      "bookmarks": []
    },
    {
      "id": "2280bb55-0b16-40cd-8beb-e19c8eb5b264",
      "title": "Linear combination of one-step predictive information with an external reward in an episodic policy gradient setting: a critical analysis",
      "abstract": "One of the main challenges in the field of embodied artificial intelligence ...",
      "authors": ["Keyan Zahedi", "Georg Martius", "Nihat Ay"],
      "source": "Science direct",
      "url": "http://arxiv.org/abs/1309.6989v1",
      "pdf_url": "http://arxiv.org/pdf/1309.6989v1",
      "categories": ["ML"],
      "publication_date": "2025-01-10",
      "created_at": "2025-01-16T09:33:48.121812Z",
      "is_bookmarked": false,
      "bookmark_id": null,
      "active_bookmarks_count": 0,
      "bookmarks": []
    },
    {
      "id": "520336eb-f9e2-4f19-84b3-660337521bd3",
      "title": "Bounded Approximate Symbolic Dynamic Programming for Hybrid MDPs",
      "abstract": "Recent advances in symbolic dynamic programming (SDP) combined with the extended algebraic decision diagram (XADD) ...",
      "authors": ["Luis Gustavo Vianna", "Scott Sanner", "Leliane Nunes de Barros"],
      "source": "Science direct",
      "url": "http://arxiv.org/abs/1309.6871v1",
      "pdf_url": "http://arxiv.org/pdf/1309.6871v1",
      "categories": ["Artificial"],
      "publication_date": "2025-01-10",
      "created_at": "2025-01-16T09:33:48.049890Z",
      "is_bookmarked": false,
      "bookmark_id": null,
      "active_bookmarks_count": 0,
      "bookmarks": []
    }
  ];
  